name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Test
      run: mvn test -Dtest="com.advella.**"
    - name: Build
      run: mvn clean install

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          connect_timeout: 200m
          script: |
            sudo chmod +x /opt/deploy.sh
            sh /opt/deploy.sh
