name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        
    - name: Replace secrets
      run: |
        sed -i -e 's/${DB_HOST}/${{ secrets.DB_HOST }}/g' ${GITHUB_WORKSPACE}/src/main/resources/application.properties
        sed -i -e 's/${DB_NAME}/${{ secrets.DB_NAME }}/g' ${GITHUB_WORKSPACE}/src/main/resources/application.properties
        sed -i -e 's/${DB_PASS}/${{ secrets.DB_PASS }}/g' ${GITHUB_WORKSPACE}/src/main/resources/application.properties
        sed -i -e 's/${DB_USER}/${{ secrets.DB_USER }}/g' ${GITHUB_WORKSPACE}/src/main/resources/application.properties

    - name: Test and Build
      run: mvn clean install

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command_timeout: 200m
          script: |
            docker build https://github.com/group27-endgame/advella-backend.git#main -t advella-backend
            
            docker rm -f advella-backend
            
            docker run -d \
            --name=advella-backend \
            --network=advella \
            -p 3000:8080 \
            -v advella-backend-vol:/app/static
            --restart unless-stopped \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASS=${{ secrets.DB_PASS }} \
            advella-backend
            
